/**
 * VERIFIED PROJECT CORPUS — the audited fallback archive.
 *
 * Source of truth: supabase/migrations/20260903120300_phase6i_project_corpus.sql
 * (86 documented records, transcribed line-by-line from DOC B pp.8-9, DOC A
 * p17 and DOC C p8 — no invented values) with the publication/verification
 * dispositions of 20260903130000_phase7a_content_population.sql applied:
 *
 *   published = verification_status 'verified' AND is_active  → 54 records
 *     (3 Practice-01 UG flagships + 51 Practice-02 HVAC rows) — the 5 rows
 *     held only by the disproven C16/C17 pairing-ambiguity premise were
 *     published by the 2026-09-10 re-audit (JCPenney 150 TR, Pearson Noida
 *     300 TR, Pearson Bangalore 120 TR, Golder Associates 12 TR, Prakash
 *     Gen-Tech 10 TR — each pairing verified by baseline-row alignment).
 *   hidden    = needs_client_review / conflict-flagged (C13/C14 and the
 *               remaining C1-C7/C10 gates) / fire rows without per-record
 *               status / residential individuals → the remainder of the 89
 *               documented records, correctly absent from every public
 *               surface, including this one.
 *
 * 2026-09-08 PDF re-audit (coordinate-level re-extraction of DOC B pp.8-9):
 * every published row's scope, capacity and city re-verified correct. The
 * source_ref numbers were corrected to the true source row numbers — the
 * earlier transcription numbered several rows by publication order, not by
 * the numbers printed in the PDF (e.g. Virus-Eraser is source row #50, not
 * #26). The C16 "ambiguous pairing" flags on the hidden rows are likewise
 * resolved by the same coordinate read; those rows remain hidden pending the
 * same client-review gates as before — this file carries only corrections.
 *
 * Every row carries its source_ref. When the Phase 6/7 entity tables are
 * applied to the live database, site-data.ts reads them FIRST (RLS enforces
 * the same verified+active matrix) and this module stops being used — no
 * route or component references it directly.
 *
 * 2026-09-10 ONGOING PUBLICATION: the client confirmed the DOC C p8 §4.2
 * "Major Projects Running" records are still ongoing (resolving review gate
 * #11 for these rows). Six records published as status "ongoing": the
 * Gurugram 60 KM package-08 row (the completed-table package-06 row remains
 * hidden — same scope, unexplained package split, C13) plus Dhanbad,
 * Aurangabad, Sangli, Bhutani 33 kV and Capgemini 11 kV. No completion
 * dates, progress percentages or phases are stated anywhere in the source —
 * the public language is "ongoing" and nothing more. The ongoing set was
 * transcribed from the same migration SQL row data (20260903120300 §P01
 * running rows + its services/sectors/clients junction inserts).
 *

 * Placeholder imagery: `image` maps a record to one of the four atmospheric
 * reference frames shared with the homepage (service-*.jpg). These are
 * implementation material only — always captioned as reference imagery,
 * never presented as project photography. Replace by reading the media
 * library (hero_media_id) when approved photography arrives.
 */

export type CorpusMetric = { label: string; value: string; unit: string };
export type CorpusRef = { name: string; slug: string };

export type ProjectRecord = {
  /** Sheet number, e.g. P1-003 — the mono figure of record. */
  ref: string;
  title: string;
  slug: string;
  practice: 1 | 2;
  practice_label: string;
  practice_name: string;
  practice_slug: string;
  city: string;
  state: string;
  status: "completed" | "ongoing" | "unconfirmed";
  scope_line: string;
  metrics: CorpusMetric[];
  client_display: string | null;
  services: CorpusRef[];
  sectors: CorpusRef[];
  featured: boolean;
  /** Atmosphere frame key — implementation material, not project photography. */
  image: "ug" | "electrical" | "cleanroom" | "fire";
  source_ref: string;
};

export const CORPUS_SOURCE_NOTE =
  "Corpus transcribed from company records DOC B pp.8-9, DOC A p17 and DOC C p8; publication states per the Phase 7 verification matrix.";

export const CORPUS_TOTAL_DOCUMENTED = 92;

/** Atmosphere frame → asset path (shared with the locked homepage). */
export const CORPUS_IMAGE: Record<ProjectRecord["image"], string> = {
  ug: "/uploads/service-ug.jpg",
  electrical: "/uploads/service-electrical.jpg",
  cleanroom: "/uploads/service-cleanroom.jpg",
  fire: "/uploads/service-fire.jpg",
};

export const PROJECT_CORPUS: ProjectRecord[] = [
  {
    ref: "P1-001",
    title: "Patna Smart City Electrical Work",
    slug: "patna-smart-city-electrical",
    practice: 1,
    practice_label: "UG Utilities & Electrical",
    practice_name: "UG Utilities, Electrical & CGD",
    practice_slug: "ug-utilities-electrical",
    city: "Patna",
    state: "Bihar",
    status: "completed",
    scope_line: "150 KM 11&33 KV cable laying",
    metrics: [
      { label: "Cable laid", value: "150", unit: "KM" },
      { label: "Voltage class", value: "11/33", unit: "KV" },
    ],
    client_display: "L&T",
    services: [{ name: "UG HT/LT Cable Laying", slug: "ug-ht-lt-cable-laying" }],
    sectors: [{ name: "Smart-City & Metro Infrastructure", slug: "smart-city-metro" }],
    featured: true,
    image: "ug",
    source_ref: "DOC C p8 §4.1 #1 — client L&T",
  },
  {
    ref: "P1-002",
    title: "Banaras Smart City Electrical Work",
    slug: "banaras-smart-city-electrical",
    practice: 1,
    practice_label: "UG Utilities & Electrical",
    practice_name: "UG Utilities, Electrical & CGD",
    practice_slug: "ug-utilities-electrical",
    city: "Banaras",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "180 KM 11/33 KV cable laying",
    metrics: [
      { label: "Cable laid", value: "180", unit: "KM" },
      { label: "Voltage class", value: "11/33", unit: "KV" },
    ],
    client_display: "L&T",
    services: [{ name: "UG HT/LT Cable Laying", slug: "ug-ht-lt-cable-laying" }],
    sectors: [{ name: "Smart-City & Metro Infrastructure", slug: "smart-city-metro" }],
    featured: true,
    image: "ug",
    source_ref: "DOC C p8 §4.1 #2 — client L&T",
  },
  {
    ref: "P1-003",
    title: "Lucknow Metro Connectivity Electrical Work",
    slug: "lucknow-metro-electrical",
    practice: 1,
    practice_label: "UG Utilities & Electrical",
    practice_name: "UG Utilities, Electrical & CGD",
    practice_slug: "ug-utilities-electrical",
    city: "Lucknow",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "20 KM 220 KV cable laying",
    metrics: [
      { label: "Cable laid", value: "20", unit: "KM" },
      { label: "Voltage class", value: "220", unit: "KV" },
    ],
    client_display: "L&T",
    services: [{ name: "UG HT/LT Cable Laying", slug: "ug-ht-lt-cable-laying" }],
    sectors: [{ name: "Smart-City & Metro Infrastructure", slug: "smart-city-metro" }],
    featured: false,
    image: "electrical",
    source_ref: "DOC C p8 §4.1 #3 — client L&T",
  },
  {
    ref: "P2-001",
    title: "World Trade Tower — HVAC & Fire",
    slug: "world-trade-tower-hvac-fire",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "4,000 TR HVAC with integrated fire hydrant & sprinkler system",
    metrics: [{ label: "Capacity", value: "4,000", unit: "TR" }],
    client_display: "World Trade Tower (WTT)",
    services: [
      { name: "HVAC Systems", slug: "hvac-systems" },
      { name: "Fire Fighting & Hydrant Systems", slug: "fire-fighting-hydrant" },
      { name: "Testing & Commissioning", slug: "testing-commissioning" },
    ],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: true,
    image: "cleanroom",
    source_ref: "DOC B p8 #01 / DOC A p16 — flagship; Template-B candidate (narrative requested)",
  },
  {
    ref: "P2-002",
    title: "World Trade Park — HVAC",
    slug: "world-trade-park-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Jaipur",
    state: "Rajasthan",
    status: "completed",
    scope_line: "2,400 TR HVAC system",
    metrics: [{ label: "Capacity", value: "2,400", unit: "TR" }],
    client_display: "World Trade Park (WTP)",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p8 #02",
  },
  {
    ref: "P2-003",
    title: "United Transformers — HVAC",
    slug: "united-transformers-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Jaipur",
    state: "Rajasthan",
    status: "completed",
    scope_line: "100 TR HVAC system",
    metrics: [{ label: "Capacity", value: "100", unit: "TR" }],
    client_display: "United Transformers",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [
      { name: "Industrial & Manufacturing", slug: "industrial-manufacturing" },
      { name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" },
    ],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p8 #03",
  },
  {
    ref: "P2-004",
    title: "Apollo Pipes Ltd — HVAC",
    slug: "apollo-pipes-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "300 TR HVAC system",
    metrics: [{ label: "Capacity", value: "300", unit: "TR" }],
    client_display: "Apollo Pipes Limited",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [
      { name: "Industrial & Manufacturing", slug: "industrial-manufacturing" },
      { name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" },
    ],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p8 #04",
  },
  {
    ref: "P2-006",
    title: "UltraTech — HVAC",
    slug: "ultratech-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "125 TR HVAC system",
    metrics: [{ label: "Capacity", value: "125", unit: "TR" }],
    client_display: "UltraTech",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [
      { name: "Industrial & Manufacturing", slug: "industrial-manufacturing" },
      { name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" },
    ],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p8 #06",
  },
  {
    ref: "P2-009",
    title: "SS Foods — HVAC",
    slug: "ss-foods-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "80 TR HVAC system",
    metrics: [{ label: "Capacity", value: "80", unit: "TR" }],
    client_display: "SS Foods",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [
      { name: "Industrial & Manufacturing", slug: "industrial-manufacturing" },
      { name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" },
    ],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p8 #09",
  },
  {
    ref: "P2-010",
    title: "Invenio — HVAC",
    slug: "invenio-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "80 TR HVAC system",
    metrics: [{ label: "Capacity", value: "80", unit: "TR" }],
    client_display: "Invenio",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p8 #10",
  },
  {
    ref: "P2-011",
    title: "Arkadin — HVAC",
    slug: "arkadin-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "70 TR HVAC system",
    metrics: [{ label: "Capacity", value: "70", unit: "TR" }],
    client_display: "Arkadin",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p8 #11",
  },
  {
    ref: "P2-012",
    title: "GEBTECH — HVAC",
    slug: "gebtech-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "35,000 sq.ft. HVAC installation",
    metrics: [{ label: "Area served", value: "35,000", unit: "SQ.FT." }],
    client_display: "GEBTECH",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [
      { name: "Industrial & Manufacturing", slug: "industrial-manufacturing" },
      { name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" },
    ],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p8 #12",
  },
  {
    ref: "P2-013",
    title: "Noida Towers Pvt Ltd — HVAC",
    slug: "noida-towers-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "30,000 sq.ft. HVAC installation",
    metrics: [{ label: "Area served", value: "30,000", unit: "SQ.FT." }],
    client_display: "Noida Towers Pvt Ltd.",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p8 #13",
  },
  {
    ref: "P2-014",
    title: "Nippon Steel — HVAC",
    slug: "nippon-steel-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "New Delhi",
    state: "Delhi",
    status: "completed",
    scope_line: "18,000 sq.ft. HVAC installation",
    metrics: [{ label: "Area served", value: "18,000", unit: "SQ.FT." }],
    client_display: "Nippon Steel & Sumitomo Metal",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p8 #14",
  },
  {
    ref: "P2-015",
    title: "TATA Advanced Ltd — HVAC",
    slug: "tata-advanced-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "16,000 sq.ft. HVAC installation",
    metrics: [{ label: "Area served", value: "16,000", unit: "SQ.FT." }],
    client_display: "TATA Advanced Systems",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p8 #15",
  },
  {
    ref: "P2-016",
    title: "Qatar Airways (Gurugram office) — HVAC",
    slug: "qatar-airways-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Gurugram",
    state: "Haryana",
    status: "completed",
    scope_line: "15,000 sq.ft. HVAC installation",
    metrics: [{ label: "Area served", value: "15,000", unit: "SQ.FT." }],
    client_display: "Qatar Airways",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: 'DOC B p8 #16 — "Qatar Airway" in source (C20)',
  },
  {
    ref: "P2-017",
    title: "IMGC — HVAC",
    slug: "imgc-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "14,000 sq.ft. HVAC installation",
    metrics: [{ label: "Area served", value: "14,000", unit: "SQ.FT." }],
    client_display: "IMGC",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p8 #17",
  },
  {
    ref: "P2-018",
    title: "DEN TV — HVAC",
    slug: "den-tv-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "New Delhi",
    state: "Delhi",
    status: "completed",
    scope_line: "14,000 sq.ft. HVAC installation",
    metrics: [{ label: "Area served", value: "14,000", unit: "SQ.FT." }],
    client_display: "DEN",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p8 #18",
  },
  {
    ref: "P2-019",
    title: "Regus — HVAC",
    slug: "regus-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "60 TR HVAC system",
    metrics: [{ label: "Capacity", value: "60", unit: "TR" }],
    client_display: "Regus",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p8 #19",
  },
  {
    ref: "P2-020",
    title: "CommScope — HVAC",
    slug: "commscope-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "45 TR HVAC system",
    metrics: [{ label: "Capacity", value: "45", unit: "TR" }],
    client_display: "CommScope",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: 'DOC B p8 #20 — "Comscope" in source (C20)',
  },
  {
    ref: "P2-021",
    title: "Hexagramme — HVAC",
    slug: "hexagramme-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "50 TR HVAC system",
    metrics: [{ label: "Capacity", value: "50", unit: "TR" }],
    client_display: "Hexagramme",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p8 #22",
  },
  {
    ref: "P2-022",
    title: "TATA AIG — HVAC",
    slug: "tata-aig-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "50 TR HVAC system",
    metrics: [{ label: "Capacity", value: "50", unit: "TR" }],
    client_display: "TATA AIG",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p8 #21",
  },
  {
    ref: "P2-023",
    title: "ICICI Lombard — HVAC",
    slug: "icici-lombard-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "40 TR HVAC system",
    metrics: [{ label: "Capacity", value: "40", unit: "TR" }],
    client_display: "ICICI Lombard",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #23",
  },
  {
    ref: "P2-024",
    title: "Acquisory Services — HVAC",
    slug: "acquisory-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "40 TR HVAC system",
    metrics: [{ label: "Capacity", value: "40", unit: "TR" }],
    client_display: "Acquisory",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #25",
  },
  {
    ref: "P2-025",
    title: "CHROME — HVAC",
    slug: "chrome-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "40 TR HVAC system",
    metrics: [{ label: "Capacity", value: "40", unit: "TR" }],
    client_display: "CHROME",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #24",
  },
  {
    ref: "P2-026",
    title: "Virus-Eraser — HVAC",
    slug: "virus-eraser-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "10 TR HVAC system",
    metrics: [{ label: "Capacity", value: "10", unit: "TR" }],
    client_display: "Virus-Eraser",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #50",
  },
  {
    ref: "P2-055",
    title: "JCPenney — HVAC",
    slug: "jcpenney-hvac-noida",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "150 TR HVAC system",
    metrics: [{ label: "Capacity", value: "150", unit: "TR" }],
    client_display: "JCPenney",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    // Published by the 2026-09-10 re-audit: DOC B p8 row 05 pairs "150TR" with
    // "JC Penny Noida" on one baseline row — the old C16 "ambiguous pairing" is
    // disproven by the coordinate read. ("JC Penny" in source; C20 spelling.)
    source_ref: "DOC B p8 #05 — pairing verified by row alignment (C16 resolved)",
  },
  {
    ref: "P2-056",
    title: "Pearson Education — HVAC (Noida)",
    slug: "pearson-education-hvac-noida",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "300 TR HVAC system",
    metrics: [{ label: "Capacity", value: "300", unit: "TR" }],
    client_display: "Pearson Education India Pvt. Ltd.",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    // Published by the 2026-09-10 re-audit: DOC B p8 row 04 pairs "300TR" with
    // "Pearson Education India Pvt. Ltd. Noida" on one baseline row (C16 resolved).
    source_ref: "DOC B p8 #04 — pairing verified by row alignment (C16 resolved)",
  },
  {
    ref: "P2-057",
    title: "Pearson Education — HVAC (Bangalore)",
    slug: "pearson-education-hvac-bangalore",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Bangalore",
    state: "Karnataka",
    status: "completed",
    scope_line: "120 TR HVAC system",
    metrics: [{ label: "Capacity", value: "120", unit: "TR" }],
    client_display: "Pearson Education India Pvt. Ltd.",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    // Published by the 2026-09-10 re-audit: DOC B p8 row 07 pairs "120TR" with
    // "Pearson Education India Pvt. Ltd. Bangalore" on one baseline row. The old
    // C17 hold noted only that the fire-section "05 cities" claim excludes this
    // record — which is about the fire list, not this HVAC row's validity.
    source_ref: "DOC B p8 #07 — pairing verified by row alignment (C17 note re fire list only)",
  },
  {
    ref: "P2-058",
    title: "Golder Associates — HVAC",
    slug: "golder-associates-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "12 TR HVAC system",
    metrics: [{ label: "Capacity", value: "12", unit: "TR" }],
    client_display: "Golder Associates",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    // Published by the 2026-09-10 re-audit: DOC B p9 row 45 pairs "12TR" with
    // "Golder Associates Noida" on one baseline row (C16 resolved).
    source_ref: "DOC B p9 #45 — pairing verified by row alignment (C16 resolved)",
  },
  {
    ref: "P2-059",
    title: "Prakash Gen-Tech — HVAC",
    slug: "prakash-gentech-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "10 TR HVAC system",
    metrics: [{ label: "Capacity", value: "10", unit: "TR" }],
    client_display: "Prakash Group of Industries",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    // Published by the 2026-09-10 re-audit: DOC B p9 row 49 pairs "10TR" with
    // "Prakash Generator Noida" on one baseline row (C16 resolved). Client display
    // per the DOC B p11 logo wall: "Prakash Group of Industries" (GEN-TECH —
    // "Generator and Air Power Specialists").
    source_ref: "DOC B p9 #49 — pairing verified by row alignment (C16 resolved)",
  },
  {
    ref: "P2-027",
    title: "Mr. Geocon Infra — HVAC",
    slug: "geocon-infra-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "10 TR HVAC system",
    metrics: [{ label: "Capacity", value: "10", unit: "TR" }],
    client_display: "Private residential client, Noida",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #47",
  },
  {
    ref: "P2-028",
    title: "I-Avatar — HVAC",
    slug: "i-avatar-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "10 TR HVAC system",
    metrics: [{ label: "Capacity", value: "10", unit: "TR" }],
    client_display: "I-Avatar",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #48",
  },
  {
    ref: "P2-029",
    title: "Tricon Builcon — HVAC",
    slug: "tricon-builcon-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "12 TR HVAC system",
    metrics: [{ label: "Capacity", value: "12", unit: "TR" }],
    client_display: "Tricon Builcon",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #43",
  },
  {
    ref: "P2-030",
    title: "Ishaan International — HVAC",
    slug: "ishaan-international-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "12 TR HVAC system",
    metrics: [{ label: "Capacity", value: "12", unit: "TR" }],
    client_display: "ISHAAN INTERNATIONAL",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #44",
  },
  {
    ref: "P2-034",
    title: "Residential installation — record 34",
    slug: "residential-hvac-record-34",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "15 TR HVAC system",
    metrics: [{ label: "Capacity", value: "15", unit: "TR" }],
    client_display: "Private residential client, Noida",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #34 — anonymized per P4 §19.10",
  },
  {
    ref: "P2-035",
    title: "Residential installation — record 35",
    slug: "residential-hvac-record-35",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "15 TR HVAC system",
    metrics: [{ label: "Capacity", value: "15", unit: "TR" }],
    client_display: "Private residential client, Noida",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #35 — anonymized per P4 §19.10",
  },
  {
    ref: "P2-036",
    title: "V & S SeAir Logistics — HVAC",
    slug: "vs-seair-logistics-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "20 TR HVAC system",
    metrics: [{ label: "Capacity", value: "20", unit: "TR" }],
    client_display: "V & S SeAir Logistics Pvt. Ltd",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #39",
  },
  {
    ref: "P2-037",
    title: "Paperpedia — HVAC",
    slug: "paperpedia-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "15 TR HVAC system",
    metrics: [{ label: "Capacity", value: "15", unit: "TR" }],
    client_display: "Paperpedia",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #40",
  },
  {
    ref: "P2-038",
    title: "Rama Refrigeration — HVAC",
    slug: "rama-refrigeration-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "25 TR HVAC system",
    metrics: [{ label: "Capacity", value: "25", unit: "TR" }],
    client_display: "Rama Refrigeration",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: 'DOC B p9 #38 — "Rama Refgeration" in source (C20)',
  },
  {
    ref: "P2-039",
    title: "APC — HVAC",
    slug: "apc-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "25 TR HVAC system",
    metrics: [{ label: "Capacity", value: "25", unit: "TR" }],
    client_display: "APC",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #31",
  },
  {
    ref: "P2-040",
    title: "My Desk — HVAC",
    slug: "my-desk-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "25 TR HVAC system",
    metrics: [{ label: "Capacity", value: "25", unit: "TR" }],
    client_display: "My Desk",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #30",
  },
  {
    ref: "P2-042",
    title: "Mr. R.U Khan — HVAC",
    slug: "residential-hvac-record-42",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "20 TR HVAC system",
    metrics: [{ label: "Capacity", value: "20", unit: "TR" }],
    client_display: "Private residential client, Noida",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #42 — anonymized per P4 §19.10",
  },
  {
    ref: "P2-043",
    title: "AVNET — HVAC",
    slug: "avnet-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "New Delhi",
    state: "Delhi",
    status: "completed",
    scope_line: "25 TR HVAC system",
    metrics: [{ label: "Capacity", value: "25", unit: "TR" }],
    client_display: "AVNET",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #32",
  },
  {
    ref: "P2-045",
    title: "Aditya Birla — HVAC",
    slug: "aditya-birla-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "35 TR HVAC system",
    metrics: [{ label: "Capacity", value: "35", unit: "TR" }],
    client_display: "Aditya Birla Group",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #26",
  },
  {
    ref: "P2-046",
    title: "AON Global — HVAC",
    slug: "aon-global-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "35 TR HVAC system",
    metrics: [{ label: "Capacity", value: "35", unit: "TR" }],
    client_display: "AON",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #27",
  },
  {
    ref: "P2-047",
    title: "B.L Agro — HVAC",
    slug: "bl-agro-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "20 TR HVAC system",
    metrics: [{ label: "Capacity", value: "20", unit: "TR" }],
    client_display: "B.L Agro",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [
      { name: "Industrial & Manufacturing", slug: "industrial-manufacturing" },
      { name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" },
    ],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #37",
  },
  {
    ref: "P2-048",
    title: "Softcell — HVAC",
    slug: "softcell-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "20 TR HVAC system",
    metrics: [{ label: "Capacity", value: "20", unit: "TR" }],
    client_display: "Softcell",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #35",
  },
  {
    ref: "P2-049",
    title: "Singhi & Company — HVAC",
    slug: "singhi-company-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "20 TR HVAC system",
    metrics: [{ label: "Capacity", value: "20", unit: "TR" }],
    client_display: "Singhi & Company",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #36",
  },
  {
    ref: "P2-050",
    title: "Lakhani Pvt Ltd — HVAC",
    slug: "lakhani-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Ghaziabad",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "20 TR HVAC system",
    metrics: [{ label: "Capacity", value: "20", unit: "TR" }],
    client_display: "Lakhani",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #38",
  },
  {
    ref: "P2-051",
    title: "Sandhaar Eco Green — HVAC",
    slug: "sandhaar-eco-green-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "10 TR HVAC system",
    metrics: [{ label: "Capacity", value: "10", unit: "TR" }],
    client_display: "Sandhaar Eco Green",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #52",
  },
  {
    ref: "P2-052",
    title: "Kotak Securities — HVAC",
    slug: "kotak-securities-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "10 TR HVAC system",
    metrics: [{ label: "Capacity", value: "10", unit: "TR" }],
    client_display: "Kotak Securities",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #53",
  },
  {
    ref: "P2-053",
    title: "Essar Oil — HVAC",
    slug: "essar-oil-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "10 TR HVAC system",
    metrics: [{ label: "Capacity", value: "10", unit: "TR" }],
    client_display: "Essar",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #54",
  },
  {
    ref: "P2-054",
    title: "Elcon — HVAC",
    slug: "elcon-hvac",
    practice: 2,
    practice_label: "MEP, HVAC & Fire",
    practice_name: "MEP, Fire Fighting & Fire Protection",
    practice_slug: "mep-fire-protection",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "completed",
    scope_line: "10 TR HVAC system",
    metrics: [{ label: "Capacity", value: "10", unit: "TR" }],
    client_display: "Elcon",
    services: [{ name: "HVAC Systems", slug: "hvac-systems" }],
    sectors: [{ name: "Corporate & Commercial Real Estate", slug: "corporate-commercial" }],
    featured: false,
    image: "cleanroom",
    source_ref: "DOC B p9 #51",
  },

  // ============ ONGOING — DOC C p8 §4.2 "Major Projects Running" ============
  // Published 2026-09-10: the client confirmed these records are still ongoing
  // (review gate #11 resolved for this set). Status is the single authoritative
  // "ongoing" — no dates, no progress percentages, no phases (none exist in the
  // source). Relationships follow the 6I migration's junction inserts verbatim.

  {
    ref: "P1-101",
    title: "Gurugram Smart City Electrical Work — Package 08",
    slug: "gurugram-smart-city-electrical-08",
    practice: 1,
    practice_label: "UG Utilities & Electrical",
    practice_name: "UG Utilities, Electrical & CGD",
    practice_slug: "ug-utilities-electrical",
    city: "Gurugram",
    state: "Haryana",
    status: "ongoing",
    scope_line: "60 KM 11&33 KV cable laying",
    metrics: [
      { label: "Cable laid", value: "60", unit: "KM" },
      { label: "Voltage class", value: "11/33", unit: "KV" },
    ],
    client_display: "TATA Projects",
    services: [{ name: "UG HT/LT Cable Laying", slug: "ug-ht-lt-cable-laying" }],
    sectors: [{ name: "Smart-City & Metro Infrastructure", slug: "smart-city-metro" }],
    featured: false,
    image: "electrical",
    // The completed-table package-06 row (same 60 KM scope) stays hidden — the
    // source prints both tables without explaining the package split (C13).
    source_ref:
      "DOC C p8 §4.2 #1 — client TATA PROJECTS (08); ongoing confirmed by client 2026-09-10",
  },
  {
    ref: "P1-102",
    title: "Dhanbad Smart City Electrical Work",
    slug: "dhanbad-smart-city-electrical",
    practice: 1,
    practice_label: "UG Utilities & Electrical",
    practice_name: "UG Utilities, Electrical & CGD",
    practice_slug: "ug-utilities-electrical",
    city: "Dhanbad",
    state: "Jharkhand",
    status: "ongoing",
    scope_line: "50 KM 11&33 KV cable laying",
    metrics: [
      { label: "Cable laid", value: "50", unit: "KM" },
      { label: "Voltage class", value: "11/33", unit: "KV" },
    ],
    client_display: "JSP Projects Pvt. Ltd.",
    services: [{ name: "UG HT/LT Cable Laying", slug: "ug-ht-lt-cable-laying" }],
    sectors: [{ name: "Smart-City & Metro Infrastructure", slug: "smart-city-metro" }],
    featured: false,
    image: "electrical",
    source_ref:
      "DOC C p8 §4.2 #2 — client JSP Projects Pvt Ltd; ongoing confirmed by client 2026-09-10",
  },
  {
    ref: "P1-103",
    title: "Aurangabad City MDP Pipe Laying",
    slug: "aurangabad-cmdp-pipe-laying",
    practice: 1,
    practice_label: "UG Utilities & Electrical",
    practice_name: "UG Utilities, Electrical & CGD",
    practice_slug: "ug-utilities-electrical",
    city: "Aurangabad",
    state: "Maharashtra",
    status: "ongoing",
    scope_line: "165 KM gas line",
    metrics: [{ label: "Gas line laid", value: "165", unit: "KM" }],
    client_display: "BGRL (Vichitra Construction Pvt Ltd)",
    services: [{ name: "CGD Networks", slug: "cgd-networks" }],
    sectors: [{ name: "Oil, Gas & CGD Utilities", slug: "oil-gas-cgd" }],
    featured: false,
    image: "ug",
    source_ref:
      "DOC C p8 §4.2 #3 — client BGRL (Vichitra Construction Pvt Ltd); ongoing confirmed by client 2026-09-10",
  },
  {
    ref: "P1-104",
    title: "Sangli LMC Work",
    slug: "sangli-lmc-work",
    practice: 1,
    practice_label: "UG Utilities & Electrical",
    practice_name: "UG Utilities, Electrical & CGD",
    practice_slug: "ug-utilities-electrical",
    city: "Sangli",
    state: "Maharashtra",
    status: "ongoing",
    scope_line: "5000 house & industry connections",
    metrics: [
      { label: "Connections", value: "5,000", unit: "" },
      { label: "Program", value: "LMC", unit: "" },
    ],
    client_display: "BGRL (Vichitra Construction Pvt Ltd)",
    services: [
      { name: "LMC Works", slug: "lmc-works" },
      { name: "CGD Networks", slug: "cgd-networks" },
    ],
    sectors: [{ name: "Oil, Gas & CGD Utilities", slug: "oil-gas-cgd" }],
    featured: false,
    image: "ug",
    source_ref:
      "DOC C p8 §4.2 #4 — client BGRL (Vichitra Construction Pvt Ltd); ongoing confirmed by client 2026-09-10",
  },
  {
    ref: "P1-105",
    title: "Bhutani Infra 33 kV Electrical Work",
    slug: "bhutani-infra-33kv-electrical",
    practice: 1,
    practice_label: "UG Utilities & Electrical",
    practice_name: "UG Utilities, Electrical & CGD",
    practice_slug: "ug-utilities-electrical",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "ongoing",
    scope_line: "6.8 KM",
    metrics: [
      { label: "Scope", value: "6.8", unit: "KM" },
      { label: "Voltage class", value: "33", unit: "KV" },
    ],
    client_display: "Bhutani Infra",
    services: [
      { name: "UG HT/LT Cable Laying", slug: "ug-ht-lt-cable-laying" },
      { name: "Sub-Station Construction", slug: "substation-construction" },
    ],
    sectors: [],
    featured: false,
    image: "electrical",
    source_ref:
      "DOC C p8 §4.2 #5 — via Parmesh Construction Company Ltd; ongoing confirmed by client 2026-09-10",
  },
  {
    ref: "P1-106",
    title: "Capgemini 11 kV Electrical Work",
    slug: "capgemini-11kv-electrical",
    practice: 1,
    practice_label: "UG Utilities & Electrical",
    practice_name: "UG Utilities, Electrical & CGD",
    practice_slug: "ug-utilities-electrical",
    city: "Noida",
    state: "Uttar Pradesh",
    status: "ongoing",
    scope_line: "1.8 KM",
    metrics: [
      { label: "Scope", value: "1.8", unit: "KM" },
      { label: "Voltage class", value: "11", unit: "KV" },
    ],
    client_display: "Capgemini",
    services: [
      { name: "UG HT/LT Cable Laying", slug: "ug-ht-lt-cable-laying" },
      { name: "Sub-Station Construction", slug: "substation-construction" },
    ],
    sectors: [],
    featured: false,
    image: "electrical",
    source_ref:
      "DOC C p8 §4.2 #6 — client Capgemini (NSEZ Noida); ongoing confirmed by client 2026-09-10",
  },
];
