/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as TeamRouteImport } from './routes/team'
import { Route as PracticesSlugRouteImport } from './routes/practices.$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ProjectsCompletedRouteImport } from './routes/projects.completed'
import { Route as ProjectsOngoingRouteImport } from './routes/projects.ongoing'
import { Route as SectorsIndexRouteImport } from './routes/sectors.index'
import { Route as SectorsSlugRouteImport } from './routes/sectors.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ApiSitemapXmlRouteImport } from './routes/api/sitemap.xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticesSlugRoute = PracticesSlugRouteImport.update({
  id: '/practices/$slug',
  path: '/practices/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCompletedRoute = ProjectsCompletedRouteImport.update({
  id: '/projects/completed',
  path: '/projects/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsOngoingRoute = ProjectsOngoingRouteImport.update({
  id: '/projects/ongoing',
  path: '/projects/ongoing',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsIndexRoute = SectorsIndexRouteImport.update({
  id: '/sectors/',
  path: '/sectors/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsSlugRoute = SectorsSlugRouteImport.update({
  id: '/sectors/$slug',
  path: '/sectors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapXmlRoute = ApiSitemapXmlRouteImport.update({
  id: '/api/sitemap/xml',
  path: '/api/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/credentials': typeof CredentialsRoute
  '/team': typeof TeamRoute
  '/practices/$slug': typeof PracticesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/completed': typeof ProjectsCompletedRoute
  '/projects/ongoing': typeof ProjectsOngoingRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/sectors/': typeof SectorsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/sitemap/xml': typeof ApiSitemapXmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/credentials': typeof CredentialsRoute
  '/team': typeof TeamRoute
  '/practices/$slug': typeof PracticesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/completed': typeof ProjectsCompletedRoute
  '/projects/ongoing': typeof ProjectsOngoingRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/projects': typeof ProjectsIndexRoute
  '/sectors': typeof SectorsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/api/sitemap/xml': typeof ApiSitemapXmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/credentials': typeof CredentialsRoute
  '/team': typeof TeamRoute
  '/practices/$slug': typeof PracticesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/completed': typeof ProjectsCompletedRoute
  '/projects/ongoing': typeof ProjectsOngoingRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/sectors/': typeof SectorsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/sitemap/xml': typeof ApiSitemapXmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about'
    | '/careers'
    | '/clients'
    | '/contact'
    | '/credentials'
    | '/team'
    | '/practices/$slug'
    | '/projects/$slug'
    | '/projects/completed'
    | '/projects/ongoing'
    | '/sectors/$slug'
    | '/services/$slug'
    | '/projects/'
    | '/sectors/'
    | '/services/'
    | '/api/sitemap/xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about'
    | '/careers'
    | '/clients'
    | '/contact'
    | '/credentials'
    | '/team'
    | '/practices/$slug'
    | '/projects/$slug'
    | '/projects/completed'
    | '/projects/ongoing'
    | '/sectors/$slug'
    | '/services/$slug'
    | '/projects'
    | '/sectors'
    | '/services'
    | '/api/sitemap/xml'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/about'
    | '/careers'
    | '/clients'
    | '/contact'
    | '/credentials'
    | '/team'
    | '/practices/$slug'
    | '/projects/$slug'
    | '/projects/completed'
    | '/projects/ongoing'
    | '/sectors/$slug'
    | '/services/$slug'
    | '/projects/'
    | '/sectors/'
    | '/services/'
    | '/api/sitemap/xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ClientsRoute: typeof ClientsRoute
  ContactRoute: typeof ContactRoute
  CredentialsRoute: typeof CredentialsRoute
  TeamRoute: typeof TeamRoute
  PracticesSlugRoute: typeof PracticesSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsCompletedRoute: typeof ProjectsCompletedRoute
  ProjectsOngoingRoute: typeof ProjectsOngoingRoute
  SectorsSlugRoute: typeof SectorsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SectorsIndexRoute: typeof SectorsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiSitemapXmlRoute: typeof ApiSitemapXmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practices/$slug': {
      id: '/practices/$slug'
      path: '/practices/$slug'
      fullPath: '/practices/$slug'
      preLoaderRoute: typeof PracticesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/completed': {
      id: '/projects/completed'
      path: '/projects/completed'
      fullPath: '/projects/completed'
      preLoaderRoute: typeof ProjectsCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/ongoing': {
      id: '/projects/ongoing'
      path: '/projects/ongoing'
      fullPath: '/projects/ongoing'
      preLoaderRoute: typeof ProjectsOngoingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/': {
      id: '/sectors/'
      path: '/sectors'
      fullPath: '/sectors/'
      preLoaderRoute: typeof SectorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/$slug': {
      id: '/sectors/$slug'
      path: '/sectors/$slug'
      fullPath: '/sectors/$slug'
      preLoaderRoute: typeof SectorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap/xml': {
      id: '/api/sitemap/xml'
      path: '/api/sitemap/xml'
      fullPath: '/api/sitemap/xml'
      preLoaderRoute: typeof ApiSitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ClientsRoute: ClientsRoute,
  ContactRoute: ContactRoute,
  CredentialsRoute: CredentialsRoute,
  TeamRoute: TeamRoute,
  PracticesSlugRoute: PracticesSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsCompletedRoute: ProjectsCompletedRoute,
  ProjectsOngoingRoute: ProjectsOngoingRoute,
  SectorsSlugRoute: SectorsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SectorsIndexRoute: SectorsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiSitemapXmlRoute: ApiSitemapXmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
